### PR TITLE
Split gem to avoid FFI dependency for core

### LINKED ISSUE #124: Make FFI optional
FFI has native extensions, which makes it inconvenient (to say the least) in some scenarios. On the other hand, FFI is only required on windows, or if using process_spawn, if I saw that correctly.

The two ideas for solving that I have are 
* make the gem into a "native" extension (without any C code), and only request installation of FFI on Windows, e.g. like in this [example](https://en.wikibooks.org/wiki/Ruby_Programming/RubyGems#How_to_install_different_versions_of_gems_depending_on_which_version_of_ruby_the_installee_is_using).
  In this case downstream users of childprocess would have to make sure that FFI is available, if they want to use posix_spawn. It is a relatively simple change on childprocess itself, but might not be easily discoverable by developers, and adds more hassle both when upgrading, and in future maintenance.
* move all non-ffi-using parts into a childprocess-core gem that can be used standalone, and have the main childprocess gem pull that in.
  This version requires more work on childprocess' side to tear apart the FFI, and non-FFI parts (although the AbstractProcess already has all the seams built in), as well as additional effort in keeping the releases in sync, and the overhead of having to release two gems instead of one. It would be a mostly transparent change to users of childprocess. Notably the generated API docs will be worse off, being split over two gems.

Personally I would prefer the split over the native extension, since it seems less of a hassle for users in the long run. I'm willing to put in the work for either version, if you agree to one of them.

### PR DESCRIPTION
**Pull request by DavidS**
This splits off all of the pure ruby code into a childprocesscore gem that doesn't depend on FFI, thereby allowing users to trade off between full-featured, and always-deployable by depending on the right gem. It is even possible for grandchildren to add the childprocess and FFI gems on top of something using only childprocesscore to enable posix_spawn, or other platform support.

This still needs updates to the README, but I wanted to get early feedback on the details of the approach.

Fixes #124

### CODE REVIEW

**Comment by DavidS** [comment]
Another thing that needs fixed is merging coverage reports from the two parts. After some googling, the best I found was switching to codecov.io instead, which does automerging of ALL reports sent in, so it could also ingest the reports from non-default rubies, and windows into a single result.

I've played around with it a little bit at another project this morning: https://codecov.io/gh/DavidS/puppet-resource_api/commit/53af7f92b209d07bb1cac838bd9d33e06906d103/build

**Comment by enkessler** [comment]
Ah. Now it makes more sense what you wanted to do. Admittedly, I only mostly followed what your plan was when you opened the issue.

I'll take a better look later this week but, at a glance, it'd be nice if the two top level project folders were named the same as their gem (`childprocess` and `childprocess-core`) instead of `main` and `core`, respectively. Then have their `lib`s shaped in the [conventional ](http://guides.rubygems.org/name-your-gem/)fashion.

Also, please base the PR off of the development branch (`dev`) instead of the master branch.

I appreciate all of the effort!

**Comment by DavidS** [comment]
I've renamed the top-level directories, and rebased everything. That was the easy part.

I also tried to rename the ChildProcess module in core. This would split the exiting public API on the ChildProcess module across namespaces, which will have a big impact on downstream users. While I tried it out, I also found pieces where it's not really clear that the way it's setup currently makes sense in a multi-gem world. E.g. https://github.com/enkessler/childprocess/blob/master/lib/childprocess.rb#L203-L205 might need more work.

Looking at that, I wonder if splitting it even more into `childprocess-core`, `childprocess-unix`, `childprocess-posix_spawn`, `childprocess-windows`, `childprocess-jruby`, and `childprocess`. Where all the library/glue code goes into -core, each of the "drives" resides in its own "plugin", and the main gem only ties the dependencies together. For the simple case, it would still remain a dependency on `childprocess`, and a single require, that pulls in everything. Maybe I'm overthinking this :-D

**Comment by DavidS** [comment]
Something weird is still ongoing with the codcov reports (see https://codecov.io/gh/DavidS/childprocess/compare/aebb49369bcebc401f0c59af8e336d47a18944c1...59fe72a87c0264ab724f21c1f27d56971fa25434/changes), but I'll chalk that up to weirdness around the changes in the repos.
 
And appveyor failed on SSL when trying to upload reports. Everything else shows up on https://codecov.io/gh/DavidS/childprocess/commit/59fe72a87c0264ab724f21c1f27d56971fa25434/build

**Comment by enkessler** [comment]
@DavidS  The more I think about it, the more that I just want the correct version to be downloaded automatically. If they are on Windows, then they get the windows version that will have FFI as a dependency and if they are not then they get the other version.

This looks relevant: http://guides.rubygems.org/specification-reference/#platform=

**Comment by DavidS** [comment]
@enkessler something like this: https://github.com/puppetlabs/puppet-resource_api/blob/master/ext/mkrf_conf.rb ?

**Comment by enkessler** [comment]
Possibly, yes. I take it that that is a script that is kicked off during the gem installation process that conditionally triggers additional gem installations? And it looks like you are already using it, so it presumably works.

Out of curiosity, what does the console output look like for the two different installation paths?

Also, I see that this was one of your first suggestions before but I glossed over it and focused on the alternative because you said

> In this case downstream users of childprocess would have to make sure that FFI is available, if they want to use posix_spawn. It is a relatively simple change on childprocess itself, but might not be easily discoverable by developers, and adds more hassle both when upgrading, and in future maintenance.

Can you elaborate on that? What do you mean by 'available'? Won't it be downloaded the same as any other gem just, you know, conditionally?

**Comment by DavidS** [comment]
The code I linked installs a package conditionally on a platform.

If we choose to "install FFI only on windows", FFI would not be available by default for `posix_spawn`.

**Comment by DavidS** [comment]
Closing this in favour of #132

**Pull request closed without merging**
