### PR TITLE
Change 'ChildProcess#started?' to be public

### LINKED ISSUE #120: Should be a public method: `#started?`
Shouldn't querying this state be a public API call?

### PR DESCRIPTION
**Pull request by ms-ati**
Fixes #120

### CODE REVIEW

**Comment by ms-ati** [comment]
@enkessler Hmm, it appears that the build is broken on 1.9.3 and JRuby. Let me know if you fix that and I can rebase

**Comment by enkessler** [comment]
@ms-ati It looks like you fixed the 1.9.3 issue but JRuby is still being JRuby (i.e. a pain).

**Comment by ms-ati** [comment]
It appears that JRuby downloads are broken across Travis CI, and indeed, across the world:
https://github.com/travis-ci/travis-ci/issues/8446

**Comment by enkessler** [comment]
@ms-ati Could you PR this of of the development branch instead of the master branch? Thanks.

**Comment by ms-ati** [comment]
@enkessler sorry which branch? I don't see a branch named `development`, do you?

**Comment by enkessler** [comment]
It's the one called `dev`.

**Pull request closed without merging**
