### PR TITLE
Add apple m1/arm64 support

### LINKED ISSUE #176: Should work for the M1 chip, but needs to be mapped or smth
I'm on the new Mac M1

```sh
$ uname -a
Darwin MacBook-Air 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
```

Using the latest release at this time, 4.0.0

```sh
$ ruby -r childprocess -e 'p ChildProcess::VERSION'
"4.0.0"
```

It tells me the M1 doesn't have posix spawn, and then it falls back to `ForkExecProcess`

```sh
$ ruby -r childprocess -e '
   require "childprocess"
   ChildProcess.posix_spawn = true
   child = ChildProcess.build("echo", "hello world")
   puts "", "implemented with #{child.class}"
   child.io.stdout = $stdout
   child.start
'
W, [2021-03-15T22:30:38.538819 #1768]  WARN -- : posix_spawn is not yet supported on arm-macosx (arm64-darwin20), falling back to default implementation. If you believe this is an error, please file a bug at http://github.com/enkessler/childprocess/issues

implemented with ChildProcess::Unix::ForkExecProcess
hello world
```

However, when I monkey patch it to use the intel solution, it works just fine:

```sh
ruby -r childprocess -e '
   require "childprocess"
   def ChildProcess.platform_name
     "x86_64-macosx"
   end
   ChildProcess.posix_spawn = true
   child = ChildProcess.build("echo", "hello world")
   puts "implemented with #{child.class}"
   child.io.stdout = $stdout
   child.start
'
implemented with ChildProcess::Unix::PosixSpawnProcess
hello world
```

So, it feels like this should work, and there just needs to be a little bit of code to tell it how to deal with the arm-macosx chip.

-----

This causes it to print the warning in the middle of the output, which goes to my text editor, so it's showing up in the middle of my code now 😛

Untitled

### PR DESCRIPTION
**Pull request by zenspider**
Fixes #176

### CODE REVIEW

**Review by sds — APPROVED** [review]
Nice cleanup!

I will hold off on merging as @enkessler is working on migrating the test suite to GitHub Actions in #178. If they are good with merging this ahead of that work (seems like it would be fine to me) I am as well!

**Comment by enkessler** [comment]
> Nice cleanup!
> 
> I will hold off on merging as @enkessler is working on migrating the test suite to GitHub Actions in #178. If they are good with merging this ahead of that work (seems like it would be fine to me) I am as well!

@sds Yeah, go for it. It shouldn't interfere at all.

**Comment by JoshCheek** [comment]
❤️ 🙏

**Comment by zenspider** [comment]
Thank you! Could I bother you for a release? Looks clean since last.

**Comment by sds** [comment]
Released in [4.1.0](https://github.com/enkessler/childprocess/releases/tag/v4.1.0).

**Pull request merged**
